# Form implementation generated from reading ui file '.\report-content.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Report_Content(object):
    def setupUi(self, Dialog_Report_Content):
        Dialog_Report_Content.setObjectName("Dialog_Report_Content")
        Dialog_Report_Content.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog_Report_Content.resize(300, 200)
        Dialog_Report_Content.setMinimumSize(QtCore.QSize(300, 200))
        Dialog_Report_Content.setMaximumSize(QtCore.QSize(300, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_Report_Content)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_Report_Content = QtWidgets.QGroupBox(parent=Dialog_Report_Content)
        self.groupBox_Report_Content.setObjectName("groupBox_Report_Content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Report_Content)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_Table = QtWidgets.QCheckBox(parent=self.groupBox_Report_Content)
        self.checkBox_Table.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.checkBox_Table.setChecked(True)
        self.checkBox_Table.setObjectName("checkBox_Table")
        self.verticalLayout.addWidget(self.checkBox_Table)
        self.checkBox_Charts = QtWidgets.QCheckBox(parent=self.groupBox_Report_Content)
        self.checkBox_Charts.setChecked(True)
        self.checkBox_Charts.setObjectName("checkBox_Charts")
        self.verticalLayout.addWidget(self.checkBox_Charts)
        self.checkBox_Additional_Data = QtWidgets.QCheckBox(parent=self.groupBox_Report_Content)
        self.checkBox_Additional_Data.setChecked(True)
        self.checkBox_Additional_Data.setObjectName("checkBox_Additional_Data")
        self.verticalLayout.addWidget(self.checkBox_Additional_Data)
        self.checkBox_Other = QtWidgets.QCheckBox(parent=self.groupBox_Report_Content)
        self.checkBox_Other.setChecked(True)
        self.checkBox_Other.setObjectName("checkBox_Other")
        self.verticalLayout.addWidget(self.checkBox_Other)
        self.verticalLayout_2.addWidget(self.groupBox_Report_Content)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_Confirm = QtWidgets.QPushButton(parent=Dialog_Report_Content)
        self.pushButton_Confirm.setObjectName("pushButton_Confirm")
        self.horizontalLayout.addWidget(self.pushButton_Confirm)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_Report_Content)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Report_Content)

    def retranslateUi(self, Dialog_Report_Content):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Report_Content.setWindowTitle(_translate("Dialog_Report_Content", "Ustawienia raportu"))
        self.groupBox_Report_Content.setTitle(_translate("Dialog_Report_Content", "Zawartość raportu"))
        self.checkBox_Table.setText(_translate("Dialog_Report_Content", "Tabele"))
        self.checkBox_Charts.setText(_translate("Dialog_Report_Content", "Wykresy"))
        self.checkBox_Additional_Data.setText(_translate("Dialog_Report_Content", "Dane dodatkowe"))
        self.checkBox_Other.setText(_translate("Dialog_Report_Content", "Inne"))
        self.pushButton_Confirm.setText(_translate("Dialog_Report_Content", "Zatwierdź"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Report_Content = QtWidgets.QDialog()
    ui = Ui_Dialog_Report_Content()
    ui.setupUi(Dialog_Report_Content)
    Dialog_Report_Content.show()
    sys.exit(app.exec())
