# Form implementation generated from reading ui file '.\settings-general.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_App_Settings(object):
    def setupUi(self, Dialog_App_Settings):
        Dialog_App_Settings.setObjectName("Dialog_App_Settings")
        Dialog_App_Settings.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog_App_Settings.resize(400, 120)
        Dialog_App_Settings.setMinimumSize(QtCore.QSize(400, 120))
        Dialog_App_Settings.setMaximumSize(QtCore.QSize(400, 120))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog_App_Settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_App_Settings)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_App_Language = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_App_Language.setObjectName("comboBox_App_Language")
        self.verticalLayout.addWidget(self.comboBox_App_Language)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_App_Settings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_App_Theme = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_App_Theme.setObjectName("comboBox_App_Theme")
        self.verticalLayout_2.addWidget(self.comboBox_App_Theme)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_Apply = QtWidgets.QPushButton(parent=Dialog_App_Settings)
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.horizontalLayout_2.addWidget(self.pushButton_Apply)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_App_Settings)
        QtCore.QMetaObject.connectSlotsByName(Dialog_App_Settings)

    def retranslateUi(self, Dialog_App_Settings):
        _translate = QtCore.QCoreApplication.translate
        Dialog_App_Settings.setWindowTitle(_translate("Dialog_App_Settings", "Ustawienia ogólne"))
        self.groupBox.setTitle(_translate("Dialog_App_Settings", "Język interfejsu"))
        self.groupBox_2.setTitle(_translate("Dialog_App_Settings", "Motyw interfejsu"))
        self.pushButton_Apply.setText(_translate("Dialog_App_Settings", "Zastosuj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_App_Settings = QtWidgets.QDialog()
    ui = Ui_Dialog_App_Settings()
    ui.setupUi(Dialog_App_Settings)
    Dialog_App_Settings.show()
    sys.exit(app.exec())
