# Form implementation generated from reading ui file '.\loading-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Loading(object):
    def setupUi(self, Dialog_Loading):
        Dialog_Loading.setObjectName("Dialog_Loading")
        Dialog_Loading.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog_Loading.resize(472, 325)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog_Loading)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar_Progress = QtWidgets.QProgressBar(parent=Dialog_Loading)
        self.progressBar_Progress.setMinimumSize(QtCore.QSize(400, 0))
        self.progressBar_Progress.setProperty("value", 0)
        self.progressBar_Progress.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar_Progress.setObjectName("progressBar_Progress")
        self.verticalLayout.addWidget(self.progressBar_Progress)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.textBrowser_Info = QtWidgets.QTextBrowser(parent=Dialog_Loading)
        self.textBrowser_Info.setObjectName("textBrowser_Info")
        self.verticalLayout.addWidget(self.textBrowser_Info)
        self.label_Static_Test = QtWidgets.QLabel(parent=Dialog_Loading)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Static_Test.setFont(font)
        self.label_Static_Test.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Static_Test.setObjectName("label_Static_Test")
        self.verticalLayout.addWidget(self.label_Static_Test)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog_Loading)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Loading)

    def retranslateUi(self, Dialog_Loading):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Loading.setWindowTitle(_translate("Dialog_Loading", "Genrowanie wyników..."))
        self.textBrowser_Info.setHtml(_translate("Dialog_Loading", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" background-color:#ffffff;\">Trwa generowanie danych...</span></p></body></html>"))
        self.label_Static_Test.setText(_translate("Dialog_Loading", "Proszę czekać, może to potrwać kilka minut..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Loading = QtWidgets.QDialog()
    ui = Ui_Dialog_Loading()
    ui.setupUi(Dialog_Loading)
    Dialog_Loading.show()
    sys.exit(app.exec())
