# Form implementation generated from reading ui file '.\locations-list.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Location_List(object):
    def setupUi(self, Dialog_Location_List):
        Dialog_Location_List.setObjectName("Dialog_Location_List")
        Dialog_Location_List.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog_Location_List.resize(800, 600)
        Dialog_Location_List.setMinimumSize(QtCore.QSize(800, 600))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog_Location_List)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget_Locatons_List = QtWidgets.QListWidget(parent=Dialog_Location_List)
        self.listWidget_Locatons_List.setObjectName("listWidget_Locatons_List")
        self.horizontalLayout.addWidget(self.listWidget_Locatons_List)

        self.retranslateUi(Dialog_Location_List)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Location_List)

    def retranslateUi(self, Dialog_Location_List):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Location_List.setWindowTitle(_translate("Dialog_Location_List", "Wybrane lokalizacje"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Location_List = QtWidgets.QDialog()
    ui = Ui_Dialog_Location_List()
    ui.setupUi(Dialog_Location_List)
    Dialog_Location_List.show()
    sys.exit(app.exec())
