# Form implementation generated from reading ui file '.\main-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Main(object):
    def setupUi(self, MainWindow_Main):
        MainWindow_Main.setObjectName("MainWindow_Main")
        MainWindow_Main.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        MainWindow_Main.resize(800, 600)
        MainWindow_Main.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_Postal_Code = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Postal_Code.setFrame(True)
        self.lineEdit_Postal_Code.setClearButtonEnabled(True)
        self.lineEdit_Postal_Code.setObjectName("lineEdit_Postal_Code")
        self.horizontalLayout_2.addWidget(self.lineEdit_Postal_Code)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.graphicsView_Map = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView_Map.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.graphicsView_Map.setObjectName("graphicsView_Map")
        self.verticalLayout.addWidget(self.graphicsView_Map)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_Generate_Raport = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Generate_Raport.setObjectName("pushButton_Generate_Raport")
        self.horizontalLayout.addWidget(self.pushButton_Generate_Raport)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow_Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(parent=self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Settings = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Help = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow_Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_Main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Main.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow_Main)
        self.toolBar.setObjectName("toolBar")
        MainWindow_Main.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actiontestowa = QtGui.QAction(parent=MainWindow_Main)
        self.actiontestowa.setObjectName("actiontestowa")
        self.action_About_Program = QtGui.QAction(parent=MainWindow_Main)
        self.action_About_Program.setObjectName("action_About_Program")
        self.actionWyj_cie = QtGui.QAction(parent=MainWindow_Main)
        self.actionWyj_cie.setObjectName("actionWyj_cie")
        self.actionUstawienia = QtGui.QAction(parent=MainWindow_Main)
        self.actionUstawienia.setObjectName("actionUstawienia")
        self.actionRaportu = QtGui.QAction(parent=MainWindow_Main)
        self.actionRaportu.setObjectName("actionRaportu")
        self.menu_File.addAction(self.actionWyj_cie)
        self.menu_Settings.addAction(self.actionUstawienia)
        self.menu_Settings.addAction(self.actionRaportu)
        self.menu_Help.addAction(self.action_About_Program)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow_Main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Main)

    def retranslateUi(self, MainWindow_Main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Main.setWindowTitle(_translate("MainWindow_Main", "DemoG"))
        self.label.setText(_translate("MainWindow_Main", "Kod pocztowy:"))
        self.lineEdit_Postal_Code.setInputMask(_translate("MainWindow_Main", "00-000"))
        self.lineEdit_Postal_Code.setText(_translate("MainWindow_Main", "00-000"))
        self.pushButton.setText(_translate("MainWindow_Main", "Dodaj"))
        self.pushButton_2.setText(_translate("MainWindow_Main", "Lista wybranych lokalizacji"))
        self.pushButton_Generate_Raport.setText(_translate("MainWindow_Main", "Generuj raport"))
        self.menu_File.setTitle(_translate("MainWindow_Main", "Plik"))
        self.menu_Settings.setTitle(_translate("MainWindow_Main", "Ustawienia"))
        self.menu_Help.setTitle(_translate("MainWindow_Main", "Pomoc"))
        self.toolBar.setWindowTitle(_translate("MainWindow_Main", "toolBar"))
        self.actiontestowa.setText(_translate("MainWindow_Main", "testowa"))
        self.action_About_Program.setText(_translate("MainWindow_Main", "O programie..."))
        self.action_About_Program.setShortcut(_translate("MainWindow_Main", "F1"))
        self.actionWyj_cie.setText(_translate("MainWindow_Main", "Wyjście"))
        self.actionUstawienia.setText(_translate("MainWindow_Main", "Aplikacji"))
        self.actionRaportu.setText(_translate("MainWindow_Main", "Raportu"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Main = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Main()
    ui.setupUi(MainWindow_Main)
    MainWindow_Main.show()
    sys.exit(app.exec())
