# Form implementation generated from reading ui file '.\main-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Main(object):
    def setupUi(self, MainWindow_Main):
        MainWindow_Main.setObjectName("MainWindow_Main")
        MainWindow_Main.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        MainWindow_Main.resize(800, 600)
        MainWindow_Main.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_Main)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow_Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(parent=self.menubar)
        self.menutest.setObjectName("menutest")
        self.menuUstawienia = QtWidgets.QMenu(parent=self.menubar)
        self.menuUstawienia.setObjectName("menuUstawienia")
        self.menuPomoc = QtWidgets.QMenu(parent=self.menubar)
        self.menuPomoc.setObjectName("menuPomoc")
        MainWindow_Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_Main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Main.setStatusBar(self.statusbar)
        self.actiontestowa = QtGui.QAction(parent=MainWindow_Main)
        self.actiontestowa.setObjectName("actiontestowa")
        self.menubar.addAction(self.menutest.menuAction())
        self.menubar.addAction(self.menuUstawienia.menuAction())
        self.menubar.addAction(self.menuPomoc.menuAction())

        self.retranslateUi(MainWindow_Main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Main)

    def retranslateUi(self, MainWindow_Main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Main.setWindowTitle(_translate("MainWindow_Main", "DemoG"))
        self.menutest.setTitle(_translate("MainWindow_Main", "Plik"))
        self.menuUstawienia.setTitle(_translate("MainWindow_Main", "Ustawienia"))
        self.menuPomoc.setTitle(_translate("MainWindow_Main", "Pomoc"))
        self.actiontestowa.setText(_translate("MainWindow_Main", "testowa"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Main = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Main()
    ui.setupUi(MainWindow_Main)
    MainWindow_Main.show()
    sys.exit(app.exec())
